const products = [
    // Smart Phones
    {
        id: 1,
        name: "iPhone 16 Pro Max",
        price: 169900,
        rating: 4.9,
        image: "https://fdn2.gsmarena.com/vv/pics/apple/apple-iphone-15-pro-max-1.jpg",
        available: true,
        category: "Smart Phones",
        description: "A18 Pro chip, 50MP main camera, 6.9-inch ProMotion XDR display, Advanced AI features, Titanium design..."
    },
    {
        id: 2,
        name: "iPhone 16 Pro",
        price: 149900,
        rating: 4.8,
        image: "https://fdn2.gsmarena.com/vv/pics/apple/apple-iphone-15-pro-1.jpg",
        backupImage: "https://fdn2.gsmarena.com/vv/pics/apple/apple-iphone-15-pro-2.jpg",
        available: true,
        category: "Smart Phones",
        description: "A18 Pro chip, 50MP main camera, 6.1-inch ProMotion XDR display, Advanced AI features, Titanium design..."
    },
    {
        id: 3,
        name: "iPhone 16 Plus",
        price: 99900,
        rating: 4.7,
        image: "https://fdn2.gsmarena.com/vv/pics/apple/apple-iphone-15-plus-1.jpg",
        backupImage: "https://fdn2.gsmarena.com/vv/pics/apple/apple-iphone-15-plus-2.jpg",
        available: true,
        category: "Smart Phones",
        description: "A18 chip, 48MP main camera, 6.7-inch Super Retina XDR display, Advanced AI features..."
    },
    {
        id: 4,
        name: "iPhone 16",
        price: 89900,
        rating: 4.7,
        image: "https://fdn2.gsmarena.com/vv/pics/apple/apple-iphone-15-1.jpg",
        backupImage: "https://fdn2.gsmarena.com/vv/pics/apple/apple-iphone-15-2.jpg",
        available: true,
        category: "Smart Phones",
        description: "A18 chip, 48MP main camera, 6.1-inch Super Retina XDR display, Advanced AI features..."
    },
    {
        id: 5,
        name: "iPhone 15 Pro Max (256GB)",
        price: 159900,
        rating: 4.9,
        image: "https://store.storeimages.cdn-apple.com/4668/as-images.apple.com/is/iphone-15-pro-max-black-titanium-select?wid=940&hei=1112&fmt=png-alpha",
        backupImage: "https://fdn2.gsmarena.com/vv/pics/apple/apple-iphone-15-pro-max-1.jpg",
        available: true,
        category: "Smart Phones",
        description: "A17 Pro chip, 48MP camera, Natural Titanium, 6.7-inch Super Retina XDR display with ProMotion..."
    },
    {
        id: 6,
        name: "iPhone 15 Pro (256GB)",
        price: 144900,
        rating: 4.8,
        image: "https://store.storeimages.cdn-apple.com/4668/as-images.apple.com/is/iphone-15-pro-blue-titanium-select?wid=940&hei=1112&fmt=png-alpha",
        backupImage: "https://fdn2.gsmarena.com/vv/pics/apple/apple-iphone-15-pro-1.jpg",
        available: true,
        category: "Smart Phones",
        description: "A17 Pro chip, 48MP camera, Blue Titanium, 6.1-inch Super Retina XDR display..."
    },
    {
        id: 7,
        name: "iPhone 15 (128GB)",
        price: 79900,
        rating: 4.7,
        image: "https://store.storeimages.cdn-apple.com/4668/as-images.apple.com/is/iphone-15-pink-select-202309?wid=940&hei=1112&fmt=png-alpha",
        backupImage: "https://fdn2.gsmarena.com/vv/pics/apple/apple-iphone-15-1.jpg",
        available: true,
        category: "Smart Phones",
        description: "A16 Bionic, 48MP camera, Pink, 6.1-inch Super Retina XDR display..."
    },
    {
        id: 8,
        name: "Samsung Galaxy S24 Ultra",
        price: 129999,
        rating: 4.8,
        image: "https://images.samsung.com/uk/smartphones/galaxy-s24-ultra/images/galaxy-s24-ultra-highlights-kv.jpg",
        backupImage: "https://images.samsung.com/uk/smartphones/galaxy-s24-ultra/images/galaxy-s24-ultra-highlights-titanium-gray.jpg",
        available: true,
        category: "Smart Phones",
        description: "12GB RAM, 256GB Storage, Titanium Gray, Snapdragon 8 Gen 3, 200MP Camera..."
    },
    {
        id: 9,
        name: "Samsung Galaxy S24+ 5G",
        price: 99999,
        rating: 4.7,
        image: "https://m.media-amazon.com/images/I/71k3gOik46L._SL1500_.jpg",
        backupImage: "https://m.media-amazon.com/images/I/71pBKWHSUxL._SL1500_.jpg",
        available: true,
        category: "Smart Phones",
        description: "12GB RAM, 256GB Storage, Cobalt Violet, Snapdragon 8 Gen 3..."
    },
    {
        id: 10,
        name: "Samsung Galaxy S24 5G",
        price: 79999,
        rating: 4.6,
        image: "https://images.samsung.com/in/smartphones/galaxy-s24/buy/product_color_violet.png",
        backupImage: "https://images.samsung.com/in/smartphones/galaxy-s24/buy/product_color_gray.png",
        available: true,
        category: "Smart Phones",
        description: "8GB RAM, 256GB Storage, Amber Yellow, Snapdragon 8 Gen 3..."
    },
    {
        id: 11,
        name: "OnePlus 12 5G",
        price: 64999,
        rating: 4.6,
        image: "https://fdn2.gsmarena.com/vv/pics/oneplus/oneplus-12-1.jpg",
        available: true,
        category: "Smart Phones",
        description: "16GB RAM, 512GB Storage, Flowy Emerald, 4th Gen Hasselblad Camera..."
    },
    {
        id: 12,
        name: "OnePlus 12R 5G",
        price: 39999,
        rating: 4.5,
        image: "https://fdn2.gsmarena.com/vv/pics/oneplus/oneplus-12r-1.jpg",
        backupImage: "https://fdn2.gsmarena.com/vv/pics/oneplus/oneplus-12r-2.jpg",
        available: true,
        category: "Smart Phones",
        description: "8GB RAM, 128GB Storage, Cool Blue, 100W SUPERVOOC..."
    },
    {
        id: 13,
        name: "OnePlus Nord CE 3 5G",
        price: 26999,
        rating: 4.3,
        image: "https://fdn2.gsmarena.com/vv/pics/oneplus/oneplus-nord-ce3-5g-1.jpg",
        backupImage: "https://fdn2.gsmarena.com/vv/pics/oneplus/oneplus-nord-ce3-5g-2.jpg",
        available: true,
        category: "Smart Phones",
        description: "8GB RAM, 128GB Storage, Aqua Surge, 50MP Triple Camera..."
    },
    {
        id: 14,
        name: "Google Pixel 8 Pro",
        price: 106999,
        rating: 4.7,
        image: "https://fdn2.gsmarena.com/vv/pics/google/google-pixel-8-pro-1.jpg",
        available: true,
        category: "Smart Phones",
        description: "12GB RAM, 128GB Storage, Bay Blue, Google Tensor G3 chip..."
    },
    {
        id: 15,
        name: "Google Pixel 8",
        price: 75999,
        rating: 4.6,
        image: "https://fdn2.gsmarena.com/vv/pics/google/google-pixel-8-1.jpg",
        backupImage: "https://fdn2.gsmarena.com/vv/pics/google/google-pixel-8-2.jpg",
        available: true,
        category: "Smart Phones",
        description: "8GB RAM, 128GB Storage, Hazel, Google Tensor G3..."
    },
    {
        id: 16,
        name: "Nothing Phone (2)",
        price: 44999,
        rating: 4.4,
        image: "https://m.media-amazon.com/images/I/71YcPvM2j9L._SL1500_.jpg",
        backupImage: "https://m.media-amazon.com/images/I/71JSM6gKoeL._SL1500_.jpg",
        available: true,
        category: "Smart Phones",
        description: "12GB RAM, 256GB Storage, Dark Grey, Glyph Interface..."
    },
    {
        id: 17,
        name: "iQOO 12 5G",
        price: 52999,
        rating: 4.5,
        image: "https://m.media-amazon.com/images/I/61JUyx1-SbL._SL1200_.jpg",
        backupImage: "https://m.media-amazon.com/images/I/61uJcXh6wqL._SL1200_.jpg",
        available: true,
        category: "Smart Phones",
        description: "12GB RAM, 256GB Storage, Alpha Black, Snapdragon 8 Gen 3..."
    },
    {
        id: 18,
        name: "Xiaomi 13 Pro 5G",
        price: 79999,
        rating: 4.4,
        image: "https://m.media-amazon.com/images/I/71vNgTH3MzL._SL1500_.jpg",
        backupImage: "https://m.media-amazon.com/images/I/71BiCb7N5YL._SL1500_.jpg",
        available: true,
        category: "Smart Phones",
        description: "12GB RAM, 256GB Storage, Ceramic Black, Leica Professional Camera..."
    },
    {
        id: 19,
        name: "Redmi Note 13 Pro+ 5G",
        price: 31999,
        rating: 4.3,
        image: "https://fdn2.gsmarena.com/vv/pics/xiaomi/xiaomi-redmi-note-13-pro-plus-1.jpg",
        backupImage: "https://fdn2.gsmarena.com/vv/pics/xiaomi/xiaomi-redmi-note-13-pro-plus-2.jpg",
        available: true,
        category: "Smart Phones",
        description: "12GB RAM, 256GB Storage, Fusion Purple, 200MP Camera..."
    },
    {
        id: 21,
        name: "MacBook Air M3",
        price: "Coming Soon",
        rating: 4.9,
        image: "https://store.storeimages.cdn-apple.com/4668/as-images.apple.com/is/macbook-air-space-gray-select-201810?wid=904&hei=840&fmt=jpeg&qlt=90&.v=1633027804000",
        backupImage: "https://store.storeimages.cdn-apple.com/4668/as-images.apple.com/is/macbook-air-space-gray-select-201810_SW_COLOR?wid=904&hei=840&fmt=jpeg&qlt=90&.v=1633027804000",
        available: false,
        category: "Laptops",
        description: "Supercharged by M3..."
    },
    {
        id: 22,
        name: "MacBook Pro 16-inch M3 Max",
        price: 297415,
        rating: 4.9,
        image: "https://store.storeimages.cdn-apple.com/4668/as-images.apple.com/is/mbp16-spacegray-select-202310?wid=904&hei=840&fmt=jpeg&qlt=90&.v=1697311054290",
        backupImage: "https://store.storeimages.cdn-apple.com/4668/as-images.apple.com/is/mbp16-silver-select-202310?wid=904&hei=840&fmt=jpeg&qlt=90&.v=1697311054290",
        available: true,
        category: "Laptops",
        description: "M3 Max chip, 32GB RAM, 1TB SSD, Space Black, 16-inch Liquid Retina XDR display..."
    },
    {
        id: 23,
        name: "MacBook Pro 14-inch M3 Pro",
        price: 212415,
        rating: 4.8,
        image: "https://store.storeimages.cdn-apple.com/4668/as-images.apple.com/is/mbp14-spacegray-select-202310?wid=904&hei=840&fmt=jpeg&qlt=90&.v=1697311054290",
        backupImage: "https://store.storeimages.cdn-apple.com/4668/as-images.apple.com/is/mbp14-silver-select-202310?wid=904&hei=840&fmt=jpeg&qlt=90&.v=1697311054290",
        available: true,
        category: "Laptops",
        description: "M3 Pro chip, 18GB RAM, 512GB SSD, Space Black, 14-inch Liquid Retina XDR display..."
    },
    {
        id: 24,
        name: "MacBook Air 15-inch M2",
        price: 131665,
        rating: 4.8,
        image: "https://store.storeimages.cdn-apple.com/4668/as-images.apple.com/is/macbook-air-midnight-select-20220606?wid=904&hei=840&fmt=jpeg&qlt=90&.v=1653084303665",
        backupImage: "https://store.storeimages.cdn-apple.com/4668/as-images.apple.com/is/macbook-air-starlight-select-20220606?wid=904&hei=840&fmt=jpeg&qlt=90&.v=1653084303678",
        available: true,
        category: "Laptops",
        description: "M2 chip, 16GB RAM, 512GB SSD, Midnight, 15.3-inch Liquid Retina display..."
    },
    {
        id: 25,
        name: "Dell XPS 15 9530",
        price: 225242,
        rating: 4.7,
        image: "images/laptops/dell-xps-15.jpg",
        backupImage: "images/laptops/dell-xps-15-alt.jpg",
        available: true,
        category: "Laptops",
        description: "13th Gen Intel i9-13900H, 32GB RAM, 1TB SSD, RTX 4070, 15.6-inch 4K OLED Touch..."
    },
    {
        id: 26,
        name: "Dell XPS 13 Plus 9320",
        price: 152992,
        rating: 4.6,
        image: "https://i.dell.com/is/image/DellContent/content/dam/ss2/product-images/dell-client-products/notebooks/xps-notebooks/xps-13-9320/media-gallery/xs9320nt-xnb-shot-5-1-sl.psd?fmt=png-alpha&pscan=auto&scl=1&hei=402&wid=402",
        backupImage: "https://i.dell.com/is/image/DellContent/content/dam/ss2/product-images/dell-client-products/notebooks/xps-notebooks/xps-13-9320/media-gallery/xs9320nt-xnb-shot-5-2-sl.psd?fmt=png-alpha&pscan=auto&scl=1&hei=402&wid=402",
        available: true,
        category: "Laptops",
        description: "13th Gen Intel i7-1360P, 16GB RAM, 512GB SSD, 13.4-inch 4K Touch..."
    },
    {
        id: 27,
        name: "ASUS ROG Zephyrus M16",
        price: 182742,
        rating: 4.7,
        image: "images/laptops/asus-rog-zephyrus-m16.jpg",
        backupImage: "images/laptops/asus-rog-zephyrus-m16-alt.jpg",
        available: true,
        category: "Laptops",
        description: "Intel Core i9-13900H, 32GB RAM, RTX 4090, 2TB SSD, 16-inch QHD 240Hz..."
    },
    {
        id: 28,
        name: "ASUS ROG Strix SCAR 16",
        price: 233742,
        rating: 4.8,
        image: "images/laptops/asus-rog-strix-scar-16.jpg",
        backupImage: "images/laptops/asus-rog-strix-scar-16-alt.jpg",
        available: true,
        category: "Laptops",
        description: "Intel Core i9-13980HX, 32GB RAM, RTX 4080, 2TB SSD, 16-inch QHD 240Hz..."
    },
    {
        id: 29,
        name: "Lenovo Legion Pro 7",
        price: 203992,
        rating: 4.6,
        image: "images/laptops/lenovo-legion-pro-7.jpg",
        backupImage: "images/laptops/lenovo-legion-pro-7-alt.jpg",
        available: true,
        category: "Laptops",
        description: "Intel Core i9-13900HX, 32GB RAM, RTX 4070, 1TB SSD, 16-inch QHD 240Hz..."
    },
    {
        id: 30,
        name: "HP Omen 16",
        price: 135992,
        rating: 4.5,
        image: "images/laptops/hp-omen-16.jpg",
        backupImage: "images/laptops/hp-omen-16-alt.jpg",
        available: true,
        category: "Laptops",
        description: "AMD Ryzen 9 7940HS, 16GB RAM, RTX 4060, 1TB SSD, 16.1-inch QHD 165Hz..."
    },
    {
        id: 31,
        name: "MSI Raider GE78 HX",
        price: 254992,
        rating: 4.7,
        image: "images/laptops/msi-raider-ge78.jpg",
        backupImage: "images/laptops/msi-raider-ge78-alt.jpg",
        available: true,
        category: "Laptops",
        description: "Intel Core i9-13980HX, 32GB RAM, RTX 4080, 2TB SSD, 17-inch QHD+ 240Hz..."
    },
    {
        id: 32,
        name: "Acer Predator Helios 16",
        price: 152992,
        rating: 4.5,
        image: "images/laptops/acer-predator-helios-16.jpg",
        backupImage: "images/laptops/acer-predator-helios-16-alt.jpg",
        available: true,
        category: "Laptops",
        description: "Intel Core i9-13900HX, 16GB RAM, RTX 4060, 1TB SSD, 16-inch QHD 165Hz..."
    },
    {
        id: 33,
        name: "LG Gram 17",
        price: 131742,
        rating: 4.6,
        image: "images/laptops/lg-gram-17.jpg",
        backupImage: "images/laptops/lg-gram-17-alt.jpg",
        available: true,
        category: "Laptops",
        description: "Intel Core i7-1360P, 16GB RAM, 1TB SSD, 17-inch QHD+ IPS, 1.35kg..."
    },
    {
        id: 34,
        name: "Microsoft Surface Laptop Studio 2",
        price: 199742,
        rating: 4.7,
        image: "images/laptops/surface-laptop-studio-2.jpg",
        backupImage: "images/laptops/surface-laptop-studio-2-alt.jpg",
        available: true,
        category: "Laptops",
        description: "Intel Core i7-13700H, 16GB RAM, RTX 4050, 512GB SSD, 14.4-inch 120Hz Touch..."
    },
    {
        id: 35,
        name: "Razer Blade 14",
        price: 169992,
        rating: 4.5,
        image: "images/laptops/razer-blade-14.jpg",
        backupImage: "images/laptops/razer-blade-14-alt.jpg",
        available: true,
        category: "Laptops",
        description: "AMD Ryzen 9 7940HS, 16GB RAM, RTX 4060, 1TB SSD, 14-inch QHD 165Hz..."
    },
    {
        id: 36,
        name: "Lenovo ThinkPad X1 Carbon Gen 11",
        price: 157242,
        rating: 4.7,
        image: "images/laptops/lenovo-thinkpad-x1.jpg",
        backupImage: "images/laptops/lenovo-thinkpad-x1-alt.jpg",
        available: true,
        category: "Laptops",
        description: "Intel Core i7-1355U, 32GB RAM, 1TB SSD, 14-inch 2.8K OLED, 1.12kg..."
    },
    {
        id: 37,
        name: "HP Envy x360 15",
        price: 106242,
        rating: 4.4,
        image: "images/laptops/hp-envy-x360.jpg",
        backupImage: "images/laptops/hp-envy-x360-alt.jpg",
        available: true,
        category: "Laptops",
        description: "Intel Core i7-1355U, 16GB RAM, 1TB SSD, 15.6-inch OLED Touch..."
    },
    {
        id: 38,
        name: "Apple AirPods Pro (2nd Gen)",
        price: 24900,
        rating: 4.8,
        image: "https://m.media-amazon.com/images/I/61SUj2aKoEL._SL1500_.jpg",
        backupImage: "https://m.media-amazon.com/images/I/61f1YfTkTDL._SL1500_.jpg",
        available: true,
        category: "Headphones",
        description: "Active Noise Cancellation, Adaptive Transparency, H2 chip..."
    },
    {
        id: 52,
        name: "Apple AirPods Max",
        price: 59900,
        rating: 4.7,
        image: "https://m.media-amazon.com/images/I/71xEVEjRHWL._SL1500_.jpg",
        backupImage: "https://m.media-amazon.com/images/I/81THB7FkQhL._SL1500_.jpg",
        available: true,
        category: "Headphones",
        description: "Space Gray, Active Noise Cancellation, Spatial Audio..."
    },
    {
        id: 54,
        name: "Sony WH-1000XM5",
        price: 34990,
        rating: 4.9,
        image: "https://m.media-amazon.com/images/I/61+btxzpfDL._SL1500_.jpg",
        backupImage: "https://m.media-amazon.com/images/I/71o8Q5XJS5L._SL1500_.jpg",
        available: true,
        category: "Headphones",
        description: "Black, 30-hour battery, Industry-leading noise cancellation, LDAC..."
    },
    {
        id: 55,
        name: "Sony WF-1000XM5",
        price: 24990,
        image: "https://m.media-amazon.com/images/I/61f1IQkoYxL._SL1500_.jpg",
        backupImage: "https://m.media-amazon.com/images/I/71YDB2PrXLL._SL1500_.jpg",
        available: false,
        category: "Headphones",
        description: "TWS, 24-hour battery, Noise cancellation, Hi-Res Audio..."
    },
    {
        id: 56,
        name: "Bose QuietComfort Ultra",
        price: 32900,
        rating: 4.7,
        image: "https://m.media-amazon.com/images/I/61g+vs7wwEL._SL1500_.jpg",
        backupImage: "https://m.media-amazon.com/images/I/71Gr2HFO9kL._SL1500_.jpg",
        available: false,
        category: "Headphones",
        description: "White Smoke, Spatial Audio, Advanced noise cancellation, 24-hour battery..."
    },
    {
        id: 57,
        name: "Bose QuietComfort Earbuds II",
        price: 24900,
        rating: 4.6,
        image: "https://m.media-amazon.com/images/I/61ahfWO64qL._SL1500_.jpg",
        backupImage: "https://m.media-amazon.com/images/I/71ZKGDdz8dL._SL1500_.jpg",
        available: false,
        category: "Headphones",
        description: "Triple Black, CustomTune technology, 6-hour battery, IPX4..."
    },
    {
        id: 58,
        name: "Sennheiser Momentum 4",
        price: 29990,
        rating: 4.8,
        image: "https://m.media-amazon.com/images/I/71LqPZxZKWL._SL1500_.jpg",
        backupImage: "https://m.media-amazon.com/images/I/71rGj5J8vML._SL1500_.jpg",
        available: false,
        category: "Headphones"
    },
    {
        id: 59,
        name: "Sennheiser Momentum True Wireless 3",
        price: 21990,
        rating: 4.6,
        image: "https://m.media-amazon.com/images/I/71kT2yqPvUL._SL1500_.jpg",
        backupImage: "https://m.media-amazon.com/images/I/71LnL8BtHZL._SL1500_.jpg",
        available: false,
        category: "Headphones"
    },
    {
        id: 60,
        name: "Samsung Galaxy Buds2 Pro",
        price: 17990,
        rating: 4.5,
        image: "https://m.media-amazon.com/images/I/61Zy+JHdgkL._SL1500_.jpg",
        backupImage: "https://m.media-amazon.com/images/I/61G9BvuHMQL._SL1500_.jpg",
        available: false,
        category: "Headphones"
    },
    {
        id: 61,
        name: "Jabra Elite 8 Active",
        price: 17999,
        rating: 4.4,
        image: "https://m.media-amazon.com/images/I/61YUxOiYuKL._SL1500_.jpg",
        backupImage: "https://m.media-amazon.com/images/I/71aL+lv+gkL._SL1500_.jpg",
        available: false,
        category: "Headphones"
    },
    {
        id: 62,
        name: "Shure AONIC 50",
        price: 29990,
        rating: 4.7,
        image: "https://m.media-amazon.com/images/I/71jQZy3ZzxL._SL1500_.jpg",
        backupImage: "https://m.media-amazon.com/images/I/71R8qJN1zUL._SL1500_.jpg",
        available: true,
        category: "Headphones"
    },
    {
        id: 64,
        name: "Nothing Ear (2)",
        price: 9999,
        rating: 4.3,
        image: "https://m.media-amazon.com/images/I/61gScQcgafL._SL1500_.jpg",
        backupImage: "https://m.media-amazon.com/images/I/61a2y1FCADL._SL1500_.jpg",
        available: false,
        category: "Headphones"
    },
    {
        id: 65,
        name: "OnePlus Buds Pro 2",
        price: 11999,
        rating: 4.4,
        image: "https://m.media-amazon.com/images/I/61q-2yzbBtL._SL1500_.jpg",
        backupImage: "https://m.media-amazon.com/images/I/61XtQPwzqBL._SL1500_.jpg",
        available: false,
        category: "Headphones"
    },
    {
        id: 66,
        name: "Google Pixel Buds Pro",
        price: 16990,
        rating: 4.5,
        image: "https://m.media-amazon.com/images/I/61J9BzebQlL._SL1500_.jpg",
        backupImage: "https://m.media-amazon.com/images/I/61bf1g6RvDL._SL1500_.jpg",
        available: false,
        category: "Headphones"
    },
    {
        id: 67,
        name: "PS5 Console (Disc Edition)",
        price: 54990,
        rating: 4.8,
        image: "images/consoles/ps5.jpg",
        backupImage: "images/consoles/ps5-alt.jpg",
        available: true,
        category: "Game Consoles",
        description: "4K gaming, Ultra-high speed SSD, DualSense controller, 3D Audio, Ray tracing..."
    },
    {
        id: 68,
        name: "PS5 Digital Edition",
        price: 44990,
        rating: 4.7,
        image: "images/consoles/ps5-digital.jpg",
        backupImage: "images/consoles/ps5-digital-alt.jpg",
        available: true,
        category: "Game Consoles",
        description: "Digital-only gaming, 825GB SSD, DualSense controller, 4K HDR, Ray tracing..."
    },
    {
        id: 69,
        name: "Xbox Series X",
        price: 49990,
        rating: 4.7,
        image: "images/consoles/xbox-series-x.jpg",
        backupImage: "images/consoles/xbox-series-x-alt.jpg",
        available: true,
        category: "Game Consoles",
        description: "True 4K gaming, 1TB SSD, 120 FPS, Quick Resume, Dolby Vision/Atmos..."
    },
    {
        id: 70,
        name: "Xbox Series S",
        price: 29999,
        rating: 4.6,
        image: "images/consoles/xbox-series-s.jpg",
        backupImage: "images/consoles/xbox-series-s-alt.jpg",
        available: true,
        category: "Game Consoles",
        description: "Digital-only gaming, 512GB SSD, 1440p gaming, Quick Resume, Game Pass..."
    },
    {
        id: 71,
        name: "Nintendo Switch OLED Model",
        price: 31900,
        rating: 4.6,
        image: "images/consoles/nintendo-switch-oled.jpg",
        backupImage: "images/consoles/nintendo-switch-oled-alt.jpg",
        available: true,
        category: "Game Consoles",
        description: "7-inch OLED screen, 64GB storage, Enhanced audio, Wired LAN port..."
    },
    {
        id: 72,
        name: "Nintendo Switch (Standard)",
        price: 28999,
        rating: 4.5,
        image: "images/consoles/nintendo-switch.jpg",
        backupImage: "images/consoles/nintendo-switch-alt.jpg",
        available: true,
        category: "Game Consoles",
        description: "6.2-inch LCD screen, 32GB storage, TV mode, Tabletop mode, Handheld mode..."
    },
    {
        id: 73,
        name: "Nintendo Switch Lite",
        price: 19999,
        rating: 4.4,
        image: "images/consoles/nintendo-switch-lite.jpg",
        backupImage: "images/consoles/nintendo-switch-lite-alt.jpg",
        available: true,
        category: "Game Consoles",
        description: "5.5-inch screen, Built-in controls, Handheld only, 32GB storage..."
    },
    {
        id: 74,
        name: "PS5 DualSense Controller",
        price: 7999,
        discount: 25,
        rating: 4.8,
        image: "images/consoles/ps5-dualsense.jpg",
        backupImage: "images/consoles/ps5-dualsense-alt.jpg",
        available: true,
        category: "Game Consoles"
    },
    {
        id: 75,
        name: "Xbox Wireless Controller",
        price: 7499,
        discount: 20,
        rating: 4.6,
        image: "images/consoles/xbox-controller.jpg",
        backupImage: "images/consoles/xbox-controller-alt.jpg",
        available: true,
        category: "Game Consoles"
    },
    {
        id: 76,
        name: "PS5 HD Camera",
        price: 6999,
        discount: 30,
        rating: 4.4,
        image: "images/consoles/ps5-camera.jpg",
        backupImage: "images/consoles/ps5-camera-alt.jpg",
        available: true,
        category: "Game Consoles"
    },
    {
        id: 77,
        name: "PS5 DualSense Charging Station",
        price: 6999,
        discount: 30,
        rating: 4.5,
        image: "images/consoles/ps5-charging-station.jpg",
        backupImage: "images/consoles/ps5-charging-station-alt.jpg",
        available: true,
        category: "Game Consoles"
    },
    {
        id: 78,
        name: "Xbox Series X/S Storage Expansion",
        price: 23999,
        rating: 4.6,
        image: "images/consoles/xbox-storage.jpg",
        backupImage: "images/consoles/xbox-storage-alt.jpg",
        available: true,
        category: "Game Consoles"
    },
    {
        id: 79,
        name: "PS5 PULSE 3D Wireless Headset",
        price: 8999,
        rating: 4.7,
        image: "images/consoles/ps5-pulse-headset.jpg",
        backupImage: "images/consoles/ps5-pulse-headset-alt.jpg",
        available: true,
        category: "Game Consoles"
    },
    {
        id: 80,
        name: "iPhone 14 Pro Max",
        price: 127900,
        rating: 4.8,
        image: "https://m.media-amazon.com/images/I/71ZDY57yTQL._SL1500_.jpg",
        backupImage: "https://m.media-amazon.com/images/I/71yzJoE7WlL._SL1500_.jpg",
        available: true,
        category: "Smart Phones",
        description: "A16 Bionic chip, 48MP main camera, 6.7-inch ProMotion XDR display, Dynamic Island, Gold finish..."
    },
    {
        id: 81,
        name: "iPhone 14 Pro",
        price: 119900,
        rating: 4.8,
        image: "https://m.media-amazon.com/images/I/61XO4bORHUL._SL1500_.jpg",
        backupImage: "https://m.media-amazon.com/images/I/61nzPMNY8zL._SL1500_.jpg",
        available: true,
        category: "Smart Phones",
        description: "A16 Bionic chip, 48MP main camera, 6.1-inch ProMotion XDR display, Dynamic Island, Space Black..."
    },
    {
        id: 82,
        name: "iPhone 14 Plus",
        price: 79900,
        rating: 4.7,
        image: "https://m.media-amazon.com/images/I/61BGE6iu4AL._SL1500_.jpg",
        backupImage: "https://m.media-amazon.com/images/I/71LKW4QZYPL._SL1500_.jpg",
        available: true,
        category: "Smart Phones",
        description: "A15 Bionic chip, Dual 12MP camera system, 6.7-inch Super Retina XDR display, Blue finish..."
    },
    {
        id: 83,
        name: "iPhone 14",
        price: 69900,
        rating: 4.7,
        image: "https://m.media-amazon.com/images/I/61bK6PMOC3L._SL1500_.jpg",
        backupImage: "https://m.media-amazon.com/images/I/71657TiFeHL._SL1500_.jpg",
        available: true,
        category: "Smart Phones",
        description: "A15 Bionic chip, Dual 12MP camera system, 6.1-inch Super Retina XDR display, Midnight finish..."
    }
]; 